name: Unified Runtime

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cuda:
    name: CUDA
    uses: ./.github/workflows/build-hw-reusable.yml
    with:
      adapter_name: CUDA
      runner_name: CUDA
