name: Unified Runtime

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  source-checks:
    name: Source Checks
    uses: ./.github/workflows/source-checks.yml

  level-zero:
    name: Level Zero
    uses: ./.github/workflows/build-hw-reusable.yml
    with:
      adapter_name: L0
      runner_name: L0

  level-zero-v2:
    name: Level Zero V2
    uses: ./.github/workflows/build-hw-reusable.yml
    with:
      adapter_name: L0_V2
      runner_name: L0

  level-zero-static:
    name: Level Zero static
    uses: ./.github/workflows/build-hw-reusable.yml
    with:
      adapter_name: L0
      runner_name: L0
      static_loader: ON
      static_adapter: ON
